apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:masters
      rolearn: arn:aws:iam::651952638870:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::651952638870:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1PQ52M3C5A63G
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-31T18:12:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1195"
  uid: 92145c93-a1c7-4f6f-8d3c-97f7e20b141c
